// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eapi.proto

/*
Package pb is a generated protocol buffer package.

Version 1.0

It is generated from these files:
	eapi.proto

It has these top-level messages:
	ResolveHashParams
	ResolveHashResponse
	InspectParams
	InspectResponse
	ListLocationsParams
	ListLocationsResponse
	CreateEntityParams
	CreateEntityResponse
	Entity
	CreateAttestationParams
	ResyncPerspectiveGraphParams
	ResyncPerspectiveGraphResponse
	SyncParams
	SyncResponse
	StorageDriverStatus
	CreateAttestationResponse
	PublishEntityParams
	PublishEntityResponse
	PublishAttestationParams
	PublishAttestationResponse
	AddAttestationParams
	AddAttestationResponse
	LookupAttestationsParams
	LookupAttestationsResponse
	Error
	Perspective
	Location
	LocationURI
	EntitySecret
	Attestation
	AttestationBody
	AttestationValidity
	EntityValidity
	Policy
	TrustLevelPolicy
	RTreePolicy
	RTreePolicyStatement
	BuildRTreeParams
	BuildRTreeResponse
	VerifyProofParams
	VerifyProofResponse
	Proof
	ProofPath
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResolveHashParams struct {
	Hash        []byte       `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Perspective *Perspective `protobuf:"bytes,2,opt,name=perspective" json:"perspective,omitempty"`
}

func (m *ResolveHashParams) Reset()                    { *m = ResolveHashParams{} }
func (m *ResolveHashParams) String() string            { return proto.CompactTextString(m) }
func (*ResolveHashParams) ProtoMessage()               {}
func (*ResolveHashParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ResolveHashParams) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ResolveHashParams) GetPerspective() *Perspective {
	if m != nil {
		return m.Perspective
	}
	return nil
}

type ResolveHashResponse struct {
	Error       *Error       `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Location    *Location    `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	Entity      *Entity      `protobuf:"bytes,3,opt,name=entity" json:"entity,omitempty"`
	Attestation *Attestation `protobuf:"bytes,4,opt,name=attestation" json:"attestation,omitempty"`
}

func (m *ResolveHashResponse) Reset()                    { *m = ResolveHashResponse{} }
func (m *ResolveHashResponse) String() string            { return proto.CompactTextString(m) }
func (*ResolveHashResponse) ProtoMessage()               {}
func (*ResolveHashResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResolveHashResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ResolveHashResponse) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *ResolveHashResponse) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *ResolveHashResponse) GetAttestation() *Attestation {
	if m != nil {
		return m.Attestation
	}
	return nil
}

type InspectParams struct {
	Content     []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ProverKey   []byte `protobuf:"bytes,2,opt,name=proverKey,proto3" json:"proverKey,omitempty"`
	VerifierKey []byte `protobuf:"bytes,3,opt,name=verifierKey,proto3" json:"verifierKey,omitempty"`
}

func (m *InspectParams) Reset()                    { *m = InspectParams{} }
func (m *InspectParams) String() string            { return proto.CompactTextString(m) }
func (*InspectParams) ProtoMessage()               {}
func (*InspectParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InspectParams) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *InspectParams) GetProverKey() []byte {
	if m != nil {
		return m.ProverKey
	}
	return nil
}

func (m *InspectParams) GetVerifierKey() []byte {
	if m != nil {
		return m.VerifierKey
	}
	return nil
}

type InspectResponse struct {
	Error       *Error       `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Entity      *Entity      `protobuf:"bytes,2,opt,name=entity" json:"entity,omitempty"`
	Attestation *Attestation `protobuf:"bytes,3,opt,name=attestation" json:"attestation,omitempty"`
}

func (m *InspectResponse) Reset()                    { *m = InspectResponse{} }
func (m *InspectResponse) String() string            { return proto.CompactTextString(m) }
func (*InspectResponse) ProtoMessage()               {}
func (*InspectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InspectResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *InspectResponse) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *InspectResponse) GetAttestation() *Attestation {
	if m != nil {
		return m.Attestation
	}
	return nil
}

type ListLocationsParams struct {
}

func (m *ListLocationsParams) Reset()                    { *m = ListLocationsParams{} }
func (m *ListLocationsParams) String() string            { return proto.CompactTextString(m) }
func (*ListLocationsParams) ProtoMessage()               {}
func (*ListLocationsParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ListLocationsResponse struct {
	Error          *Error               `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	AgentLocations map[string]*Location `protobuf:"bytes,2,rep,name=agentLocations" json:"agentLocations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ListLocationsResponse) Reset()                    { *m = ListLocationsResponse{} }
func (m *ListLocationsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListLocationsResponse) ProtoMessage()               {}
func (*ListLocationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListLocationsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ListLocationsResponse) GetAgentLocations() map[string]*Location {
	if m != nil {
		return m.AgentLocations
	}
	return nil
}

type CreateEntityParams struct {
	// Milliseconds since the epoch
	ValidFrom          int64     `protobuf:"varint,1,opt,name=validFrom" json:"validFrom,omitempty"`
	ValidUntil         int64     `protobuf:"varint,2,opt,name=validUntil" json:"validUntil,omitempty"`
	RevocationLocation *Location `protobuf:"bytes,3,opt,name=revocationLocation" json:"revocationLocation,omitempty"`
	SecretPassphrase   string    `protobuf:"bytes,4,opt,name=SecretPassphrase,json=secretPassphrase" json:"SecretPassphrase,omitempty"`
}

func (m *CreateEntityParams) Reset()                    { *m = CreateEntityParams{} }
func (m *CreateEntityParams) String() string            { return proto.CompactTextString(m) }
func (*CreateEntityParams) ProtoMessage()               {}
func (*CreateEntityParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateEntityParams) GetValidFrom() int64 {
	if m != nil {
		return m.ValidFrom
	}
	return 0
}

func (m *CreateEntityParams) GetValidUntil() int64 {
	if m != nil {
		return m.ValidUntil
	}
	return 0
}

func (m *CreateEntityParams) GetRevocationLocation() *Location {
	if m != nil {
		return m.RevocationLocation
	}
	return nil
}

func (m *CreateEntityParams) GetSecretPassphrase() string {
	if m != nil {
		return m.SecretPassphrase
	}
	return ""
}

type CreateEntityResponse struct {
	Error     *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	PublicDER []byte `protobuf:"bytes,2,opt,name=PublicDER,json=publicDER,proto3" json:"PublicDER,omitempty"`
	SecretDER []byte `protobuf:"bytes,3,opt,name=SecretDER,json=secretDER,proto3" json:"SecretDER,omitempty"`
	Hash      []byte `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *CreateEntityResponse) Reset()                    { *m = CreateEntityResponse{} }
func (m *CreateEntityResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateEntityResponse) ProtoMessage()               {}
func (*CreateEntityResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateEntityResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *CreateEntityResponse) GetPublicDER() []byte {
	if m != nil {
		return m.PublicDER
	}
	return nil
}

func (m *CreateEntityResponse) GetSecretDER() []byte {
	if m != nil {
		return m.SecretDER
	}
	return nil
}

func (m *CreateEntityResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Entity struct {
	Hash       []byte          `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ValidFrom  int64           `protobuf:"varint,2,opt,name=validFrom" json:"validFrom,omitempty"`
	ValidUntil int64           `protobuf:"varint,3,opt,name=validUntil" json:"validUntil,omitempty"`
	Validity   *EntityValidity `protobuf:"bytes,4,opt,name=validity" json:"validity,omitempty"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Entity) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Entity) GetValidFrom() int64 {
	if m != nil {
		return m.ValidFrom
	}
	return 0
}

func (m *Entity) GetValidUntil() int64 {
	if m != nil {
		return m.ValidUntil
	}
	return 0
}

func (m *Entity) GetValidity() *EntityValidity {
	if m != nil {
		return m.Validity
	}
	return nil
}

type CreateAttestationParams struct {
	Perspective     *Perspective `protobuf:"bytes,1,opt,name=perspective" json:"perspective,omitempty"`
	BodyScheme      string       `protobuf:"bytes,2,opt,name=bodyScheme" json:"bodyScheme,omitempty"`
	SubjectHash     []byte       `protobuf:"bytes,3,opt,name=subjectHash,proto3" json:"subjectHash,omitempty"`
	SubjectLocation *Location    `protobuf:"bytes,4,opt,name=subjectLocation" json:"subjectLocation,omitempty"`
	// If 0, will be set to time.Now
	ValidFrom int64 `protobuf:"varint,5,opt,name=validFrom" json:"validFrom,omitempty"`
	// If 0, will be set to some arbitrary default
	ValidUntil int64   `protobuf:"varint,6,opt,name=validUntil" json:"validUntil,omitempty"`
	Policy     *Policy `protobuf:"bytes,7,opt,name=policy" json:"policy,omitempty"`
}

func (m *CreateAttestationParams) Reset()                    { *m = CreateAttestationParams{} }
func (m *CreateAttestationParams) String() string            { return proto.CompactTextString(m) }
func (*CreateAttestationParams) ProtoMessage()               {}
func (*CreateAttestationParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CreateAttestationParams) GetPerspective() *Perspective {
	if m != nil {
		return m.Perspective
	}
	return nil
}

func (m *CreateAttestationParams) GetBodyScheme() string {
	if m != nil {
		return m.BodyScheme
	}
	return ""
}

func (m *CreateAttestationParams) GetSubjectHash() []byte {
	if m != nil {
		return m.SubjectHash
	}
	return nil
}

func (m *CreateAttestationParams) GetSubjectLocation() *Location {
	if m != nil {
		return m.SubjectLocation
	}
	return nil
}

func (m *CreateAttestationParams) GetValidFrom() int64 {
	if m != nil {
		return m.ValidFrom
	}
	return 0
}

func (m *CreateAttestationParams) GetValidUntil() int64 {
	if m != nil {
		return m.ValidUntil
	}
	return 0
}

func (m *CreateAttestationParams) GetPolicy() *Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

type ResyncPerspectiveGraphParams struct {
	Perspective *Perspective `protobuf:"bytes,1,opt,name=perspective" json:"perspective,omitempty"`
}

func (m *ResyncPerspectiveGraphParams) Reset()                    { *m = ResyncPerspectiveGraphParams{} }
func (m *ResyncPerspectiveGraphParams) String() string            { return proto.CompactTextString(m) }
func (*ResyncPerspectiveGraphParams) ProtoMessage()               {}
func (*ResyncPerspectiveGraphParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ResyncPerspectiveGraphParams) GetPerspective() *Perspective {
	if m != nil {
		return m.Perspective
	}
	return nil
}

type ResyncPerspectiveGraphResponse struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *ResyncPerspectiveGraphResponse) Reset()                    { *m = ResyncPerspectiveGraphResponse{} }
func (m *ResyncPerspectiveGraphResponse) String() string            { return proto.CompactTextString(m) }
func (*ResyncPerspectiveGraphResponse) ProtoMessage()               {}
func (*ResyncPerspectiveGraphResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ResyncPerspectiveGraphResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type SyncParams struct {
	Perspective *Perspective `protobuf:"bytes,1,opt,name=perspective" json:"perspective,omitempty"`
}

func (m *SyncParams) Reset()                    { *m = SyncParams{} }
func (m *SyncParams) String() string            { return proto.CompactTextString(m) }
func (*SyncParams) ProtoMessage()               {}
func (*SyncParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *SyncParams) GetPerspective() *Perspective {
	if m != nil {
		return m.Perspective
	}
	return nil
}

type SyncResponse struct {
	Error             *Error                          `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	StorageStatus     map[string]*StorageDriverStatus `protobuf:"bytes,2,rep,name=storageStatus" json:"storageStatus,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TotalSyncRequests int64                           `protobuf:"varint,3,opt,name=totalSyncRequests" json:"totalSyncRequests,omitempty"`
	CompletedSyncs    int64                           `protobuf:"varint,4,opt,name=completedSyncs" json:"completedSyncs,omitempty"`
}

func (m *SyncResponse) Reset()                    { *m = SyncResponse{} }
func (m *SyncResponse) String() string            { return proto.CompactTextString(m) }
func (*SyncResponse) ProtoMessage()               {}
func (*SyncResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SyncResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SyncResponse) GetStorageStatus() map[string]*StorageDriverStatus {
	if m != nil {
		return m.StorageStatus
	}
	return nil
}

func (m *SyncResponse) GetTotalSyncRequests() int64 {
	if m != nil {
		return m.TotalSyncRequests
	}
	return 0
}

func (m *SyncResponse) GetCompletedSyncs() int64 {
	if m != nil {
		return m.CompletedSyncs
	}
	return 0
}

type StorageDriverStatus struct {
	Operational bool              `protobuf:"varint,1,opt,name=operational" json:"operational,omitempty"`
	Info        map[string]string `protobuf:"bytes,2,rep,name=info" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *StorageDriverStatus) Reset()                    { *m = StorageDriverStatus{} }
func (m *StorageDriverStatus) String() string            { return proto.CompactTextString(m) }
func (*StorageDriverStatus) ProtoMessage()               {}
func (*StorageDriverStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *StorageDriverStatus) GetOperational() bool {
	if m != nil {
		return m.Operational
	}
	return false
}

func (m *StorageDriverStatus) GetInfo() map[string]string {
	if m != nil {
		return m.Info
	}
	return nil
}

type CreateAttestationResponse struct {
	Error       *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	DER         []byte `protobuf:"bytes,2,opt,name=DER,json=dER,proto3" json:"DER,omitempty"`
	VerifierKey []byte `protobuf:"bytes,3,opt,name=verifierKey,proto3" json:"verifierKey,omitempty"`
	ProverKey   []byte `protobuf:"bytes,4,opt,name=proverKey,proto3" json:"proverKey,omitempty"`
	Hash        []byte `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *CreateAttestationResponse) Reset()                    { *m = CreateAttestationResponse{} }
func (m *CreateAttestationResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAttestationResponse) ProtoMessage()               {}
func (*CreateAttestationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CreateAttestationResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *CreateAttestationResponse) GetDER() []byte {
	if m != nil {
		return m.DER
	}
	return nil
}

func (m *CreateAttestationResponse) GetVerifierKey() []byte {
	if m != nil {
		return m.VerifierKey
	}
	return nil
}

func (m *CreateAttestationResponse) GetProverKey() []byte {
	if m != nil {
		return m.ProverKey
	}
	return nil
}

func (m *CreateAttestationResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type PublishEntityParams struct {
	DER      []byte    `protobuf:"bytes,1,opt,name=DER,json=dER,proto3" json:"DER,omitempty"`
	Location *Location `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
}

func (m *PublishEntityParams) Reset()                    { *m = PublishEntityParams{} }
func (m *PublishEntityParams) String() string            { return proto.CompactTextString(m) }
func (*PublishEntityParams) ProtoMessage()               {}
func (*PublishEntityParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PublishEntityParams) GetDER() []byte {
	if m != nil {
		return m.DER
	}
	return nil
}

func (m *PublishEntityParams) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type PublishEntityResponse struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Hash  []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *PublishEntityResponse) Reset()                    { *m = PublishEntityResponse{} }
func (m *PublishEntityResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishEntityResponse) ProtoMessage()               {}
func (*PublishEntityResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PublishEntityResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *PublishEntityResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type PublishAttestationParams struct {
	DER      []byte    `protobuf:"bytes,1,opt,name=DER,json=dER,proto3" json:"DER,omitempty"`
	Location *Location `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
}

func (m *PublishAttestationParams) Reset()                    { *m = PublishAttestationParams{} }
func (m *PublishAttestationParams) String() string            { return proto.CompactTextString(m) }
func (*PublishAttestationParams) ProtoMessage()               {}
func (*PublishAttestationParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *PublishAttestationParams) GetDER() []byte {
	if m != nil {
		return m.DER
	}
	return nil
}

func (m *PublishAttestationParams) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type PublishAttestationResponse struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Hash  []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *PublishAttestationResponse) Reset()                    { *m = PublishAttestationResponse{} }
func (m *PublishAttestationResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishAttestationResponse) ProtoMessage()               {}
func (*PublishAttestationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *PublishAttestationResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *PublishAttestationResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type AddAttestationParams struct {
	Perspective *Perspective `protobuf:"bytes,1,opt,name=perspective" json:"perspective,omitempty"`
	DER         []byte       `protobuf:"bytes,2,opt,name=DER,json=dER,proto3" json:"DER,omitempty"`
	ProverKey   []byte       `protobuf:"bytes,3,opt,name=proverKey,proto3" json:"proverKey,omitempty"`
}

func (m *AddAttestationParams) Reset()                    { *m = AddAttestationParams{} }
func (m *AddAttestationParams) String() string            { return proto.CompactTextString(m) }
func (*AddAttestationParams) ProtoMessage()               {}
func (*AddAttestationParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *AddAttestationParams) GetPerspective() *Perspective {
	if m != nil {
		return m.Perspective
	}
	return nil
}

func (m *AddAttestationParams) GetDER() []byte {
	if m != nil {
		return m.DER
	}
	return nil
}

func (m *AddAttestationParams) GetProverKey() []byte {
	if m != nil {
		return m.ProverKey
	}
	return nil
}

type AddAttestationResponse struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *AddAttestationResponse) Reset()                    { *m = AddAttestationResponse{} }
func (m *AddAttestationResponse) String() string            { return proto.CompactTextString(m) }
func (*AddAttestationResponse) ProtoMessage()               {}
func (*AddAttestationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *AddAttestationResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type LookupAttestationsParams struct {
	Perspective *Perspective `protobuf:"bytes,1,opt,name=perspective" json:"perspective,omitempty"`
	FromEntity  []byte       `protobuf:"bytes,2,opt,name=fromEntity,proto3" json:"fromEntity,omitempty"`
	ToEntity    []byte       `protobuf:"bytes,3,opt,name=toEntity,proto3" json:"toEntity,omitempty"`
}

func (m *LookupAttestationsParams) Reset()                    { *m = LookupAttestationsParams{} }
func (m *LookupAttestationsParams) String() string            { return proto.CompactTextString(m) }
func (*LookupAttestationsParams) ProtoMessage()               {}
func (*LookupAttestationsParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *LookupAttestationsParams) GetPerspective() *Perspective {
	if m != nil {
		return m.Perspective
	}
	return nil
}

func (m *LookupAttestationsParams) GetFromEntity() []byte {
	if m != nil {
		return m.FromEntity
	}
	return nil
}

func (m *LookupAttestationsParams) GetToEntity() []byte {
	if m != nil {
		return m.ToEntity
	}
	return nil
}

type LookupAttestationsResponse struct {
	Error   *Error         `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Results []*Attestation `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
}

func (m *LookupAttestationsResponse) Reset()                    { *m = LookupAttestationsResponse{} }
func (m *LookupAttestationsResponse) String() string            { return proto.CompactTextString(m) }
func (*LookupAttestationsResponse) ProtoMessage()               {}
func (*LookupAttestationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *LookupAttestationsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *LookupAttestationsResponse) GetResults() []*Attestation {
	if m != nil {
		return m.Results
	}
	return nil
}

type Error struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Perspective struct {
	EntitySecret *EntitySecret `protobuf:"bytes,1,opt,name=entitySecret" json:"entitySecret,omitempty"`
	Location     *Location     `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
}

func (m *Perspective) Reset()                    { *m = Perspective{} }
func (m *Perspective) String() string            { return proto.CompactTextString(m) }
func (*Perspective) ProtoMessage()               {}
func (*Perspective) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *Perspective) GetEntitySecret() *EntitySecret {
	if m != nil {
		return m.EntitySecret
	}
	return nil
}

func (m *Perspective) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Location struct {
	// One of the following
	LocationURI *LocationURI `protobuf:"bytes,1,opt,name=locationURI" json:"locationURI,omitempty"`
	// The name of a location in the agent config
	AgentLocation string `protobuf:"bytes,2,opt,name=agentLocation" json:"agentLocation,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *Location) GetLocationURI() *LocationURI {
	if m != nil {
		return m.LocationURI
	}
	return nil
}

func (m *Location) GetAgentLocation() string {
	if m != nil {
		return m.AgentLocation
	}
	return ""
}

type LocationURI struct {
	URI     string `protobuf:"bytes,1,opt,name=URI,json=uRI" json:"URI,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *LocationURI) Reset()                    { *m = LocationURI{} }
func (m *LocationURI) String() string            { return proto.CompactTextString(m) }
func (*LocationURI) ProtoMessage()               {}
func (*LocationURI) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *LocationURI) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *LocationURI) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type EntitySecret struct {
	DER        []byte `protobuf:"bytes,1,opt,name=DER,json=dER,proto3" json:"DER,omitempty"`
	Passphrase []byte `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
}

func (m *EntitySecret) Reset()                    { *m = EntitySecret{} }
func (m *EntitySecret) String() string            { return proto.CompactTextString(m) }
func (*EntitySecret) ProtoMessage()               {}
func (*EntitySecret) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *EntitySecret) GetDER() []byte {
	if m != nil {
		return m.DER
	}
	return nil
}

func (m *EntitySecret) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

type Attestation struct {
	DER             []byte               `protobuf:"bytes,1,opt,name=DER,json=dER,proto3" json:"DER,omitempty"`
	Hash            []byte               `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Body            *AttestationBody     `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	VerifierKey     []byte               `protobuf:"bytes,4,opt,name=verifierKey,proto3" json:"verifierKey,omitempty"`
	ProverKey       []byte               `protobuf:"bytes,5,opt,name=proverKey,proto3" json:"proverKey,omitempty"`
	SubjectHash     []byte               `protobuf:"bytes,6,opt,name=subjectHash,proto3" json:"subjectHash,omitempty"`
	SubjectLocation *Location            `protobuf:"bytes,7,opt,name=subjectLocation" json:"subjectLocation,omitempty"`
	Validity        *AttestationValidity `protobuf:"bytes,8,opt,name=validity" json:"validity,omitempty"`
	Partition       [][]byte             `protobuf:"bytes,9,rep,name=partition,proto3" json:"partition,omitempty"`
}

func (m *Attestation) Reset()                    { *m = Attestation{} }
func (m *Attestation) String() string            { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()               {}
func (*Attestation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *Attestation) GetDER() []byte {
	if m != nil {
		return m.DER
	}
	return nil
}

func (m *Attestation) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Attestation) GetBody() *AttestationBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Attestation) GetVerifierKey() []byte {
	if m != nil {
		return m.VerifierKey
	}
	return nil
}

func (m *Attestation) GetProverKey() []byte {
	if m != nil {
		return m.ProverKey
	}
	return nil
}

func (m *Attestation) GetSubjectHash() []byte {
	if m != nil {
		return m.SubjectHash
	}
	return nil
}

func (m *Attestation) GetSubjectLocation() *Location {
	if m != nil {
		return m.SubjectLocation
	}
	return nil
}

func (m *Attestation) GetValidity() *AttestationValidity {
	if m != nil {
		return m.Validity
	}
	return nil
}

func (m *Attestation) GetPartition() [][]byte {
	if m != nil {
		return m.Partition
	}
	return nil
}

type AttestationBody struct {
	DecodedBodyDER   []byte    `protobuf:"bytes,1,opt,name=DecodedBodyDER,json=decodedBodyDER,proto3" json:"DecodedBodyDER,omitempty"`
	AttesterHash     []byte    `protobuf:"bytes,2,opt,name=attesterHash,proto3" json:"attesterHash,omitempty"`
	AttesterLocation *Location `protobuf:"bytes,3,opt,name=attesterLocation" json:"attesterLocation,omitempty"`
	Policy           *Policy   `protobuf:"bytes,4,opt,name=policy" json:"policy,omitempty"`
	ValidFrom        int64     `protobuf:"varint,5,opt,name=validFrom" json:"validFrom,omitempty"`
	ValidUntil       int64     `protobuf:"varint,6,opt,name=validUntil" json:"validUntil,omitempty"`
}

func (m *AttestationBody) Reset()                    { *m = AttestationBody{} }
func (m *AttestationBody) String() string            { return proto.CompactTextString(m) }
func (*AttestationBody) ProtoMessage()               {}
func (*AttestationBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *AttestationBody) GetDecodedBodyDER() []byte {
	if m != nil {
		return m.DecodedBodyDER
	}
	return nil
}

func (m *AttestationBody) GetAttesterHash() []byte {
	if m != nil {
		return m.AttesterHash
	}
	return nil
}

func (m *AttestationBody) GetAttesterLocation() *Location {
	if m != nil {
		return m.AttesterLocation
	}
	return nil
}

func (m *AttestationBody) GetPolicy() *Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *AttestationBody) GetValidFrom() int64 {
	if m != nil {
		return m.ValidFrom
	}
	return 0
}

func (m *AttestationBody) GetValidUntil() int64 {
	if m != nil {
		return m.ValidUntil
	}
	return 0
}

type AttestationValidity struct {
	Valid        bool   `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Revoked      bool   `protobuf:"varint,2,opt,name=revoked" json:"revoked,omitempty"`
	Expired      bool   `protobuf:"varint,3,opt,name=expired" json:"expired,omitempty"`
	Malformed    bool   `protobuf:"varint,4,opt,name=malformed" json:"malformed,omitempty"`
	NotDecrypted bool   `protobuf:"varint,5,opt,name=notDecrypted" json:"notDecrypted,omitempty"`
	SrcInvalid   bool   `protobuf:"varint,6,opt,name=srcInvalid" json:"srcInvalid,omitempty"`
	DstInvalid   bool   `protobuf:"varint,7,opt,name=dstInvalid" json:"dstInvalid,omitempty"`
	Message      string `protobuf:"bytes,8,opt,name=message" json:"message,omitempty"`
}

func (m *AttestationValidity) Reset()                    { *m = AttestationValidity{} }
func (m *AttestationValidity) String() string            { return proto.CompactTextString(m) }
func (*AttestationValidity) ProtoMessage()               {}
func (*AttestationValidity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *AttestationValidity) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *AttestationValidity) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *AttestationValidity) GetExpired() bool {
	if m != nil {
		return m.Expired
	}
	return false
}

func (m *AttestationValidity) GetMalformed() bool {
	if m != nil {
		return m.Malformed
	}
	return false
}

func (m *AttestationValidity) GetNotDecrypted() bool {
	if m != nil {
		return m.NotDecrypted
	}
	return false
}

func (m *AttestationValidity) GetSrcInvalid() bool {
	if m != nil {
		return m.SrcInvalid
	}
	return false
}

func (m *AttestationValidity) GetDstInvalid() bool {
	if m != nil {
		return m.DstInvalid
	}
	return false
}

func (m *AttestationValidity) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EntityValidity struct {
	Valid     bool   `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Revoked   bool   `protobuf:"varint,2,opt,name=revoked" json:"revoked,omitempty"`
	Expired   bool   `protobuf:"varint,3,opt,name=expired" json:"expired,omitempty"`
	Malformed bool   `protobuf:"varint,4,opt,name=malformed" json:"malformed,omitempty"`
	Message   string `protobuf:"bytes,5,opt,name=message" json:"message,omitempty"`
}

func (m *EntityValidity) Reset()                    { *m = EntityValidity{} }
func (m *EntityValidity) String() string            { return proto.CompactTextString(m) }
func (*EntityValidity) ProtoMessage()               {}
func (*EntityValidity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *EntityValidity) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *EntityValidity) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *EntityValidity) GetExpired() bool {
	if m != nil {
		return m.Expired
	}
	return false
}

func (m *EntityValidity) GetMalformed() bool {
	if m != nil {
		return m.Malformed
	}
	return false
}

func (m *EntityValidity) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Policy struct {
	TrustLevelPolicy *TrustLevelPolicy `protobuf:"bytes,1,opt,name=trustLevelPolicy" json:"trustLevelPolicy,omitempty"`
	RTreePolicy      *RTreePolicy      `protobuf:"bytes,2,opt,name=rTreePolicy" json:"rTreePolicy,omitempty"`
}

func (m *Policy) Reset()                    { *m = Policy{} }
func (m *Policy) String() string            { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()               {}
func (*Policy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *Policy) GetTrustLevelPolicy() *TrustLevelPolicy {
	if m != nil {
		return m.TrustLevelPolicy
	}
	return nil
}

func (m *Policy) GetRTreePolicy() *RTreePolicy {
	if m != nil {
		return m.RTreePolicy
	}
	return nil
}

type TrustLevelPolicy struct {
	Trust int32 `protobuf:"varint,1,opt,name=trust" json:"trust,omitempty"`
}

func (m *TrustLevelPolicy) Reset()                    { *m = TrustLevelPolicy{} }
func (m *TrustLevelPolicy) String() string            { return proto.CompactTextString(m) }
func (*TrustLevelPolicy) ProtoMessage()               {}
func (*TrustLevelPolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *TrustLevelPolicy) GetTrust() int32 {
	if m != nil {
		return m.Trust
	}
	return 0
}

type RTreePolicy struct {
	Namespace     []byte                  `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Indirections  uint32                  `protobuf:"varint,2,opt,name=indirections" json:"indirections,omitempty"`
	Statements    []*RTreePolicyStatement `protobuf:"bytes,3,rep,name=statements" json:"statements,omitempty"`
	VisibilityURI [][]byte                `protobuf:"bytes,4,rep,name=visibilityURI,proto3" json:"visibilityURI,omitempty"`
}

func (m *RTreePolicy) Reset()                    { *m = RTreePolicy{} }
func (m *RTreePolicy) String() string            { return proto.CompactTextString(m) }
func (*RTreePolicy) ProtoMessage()               {}
func (*RTreePolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *RTreePolicy) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *RTreePolicy) GetIndirections() uint32 {
	if m != nil {
		return m.Indirections
	}
	return 0
}

func (m *RTreePolicy) GetStatements() []*RTreePolicyStatement {
	if m != nil {
		return m.Statements
	}
	return nil
}

func (m *RTreePolicy) GetVisibilityURI() [][]byte {
	if m != nil {
		return m.VisibilityURI
	}
	return nil
}

type RTreePolicyStatement struct {
	PermissionSet []byte   `protobuf:"bytes,1,opt,name=permissionSet,proto3" json:"permissionSet,omitempty"`
	Permissions   []string `protobuf:"bytes,2,rep,name=permissions" json:"permissions,omitempty"`
	Resource      string   `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
}

func (m *RTreePolicyStatement) Reset()                    { *m = RTreePolicyStatement{} }
func (m *RTreePolicyStatement) String() string            { return proto.CompactTextString(m) }
func (*RTreePolicyStatement) ProtoMessage()               {}
func (*RTreePolicyStatement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *RTreePolicyStatement) GetPermissionSet() []byte {
	if m != nil {
		return m.PermissionSet
	}
	return nil
}

func (m *RTreePolicyStatement) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *RTreePolicyStatement) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type BuildRTreeParams struct {
	Perspective    *Perspective            `protobuf:"bytes,1,opt,name=perspective" json:"perspective,omitempty"`
	SubjectHash    []byte                  `protobuf:"bytes,2,opt,name=subjectHash,proto3" json:"subjectHash,omitempty"`
	RtreeNamespace []byte                  `protobuf:"bytes,3,opt,name=rtreeNamespace,proto3" json:"rtreeNamespace,omitempty"`
	Statements     []*RTreePolicyStatement `protobuf:"bytes,4,rep,name=statements" json:"statements,omitempty"`
}

func (m *BuildRTreeParams) Reset()                    { *m = BuildRTreeParams{} }
func (m *BuildRTreeParams) String() string            { return proto.CompactTextString(m) }
func (*BuildRTreeParams) ProtoMessage()               {}
func (*BuildRTreeParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *BuildRTreeParams) GetPerspective() *Perspective {
	if m != nil {
		return m.Perspective
	}
	return nil
}

func (m *BuildRTreeParams) GetSubjectHash() []byte {
	if m != nil {
		return m.SubjectHash
	}
	return nil
}

func (m *BuildRTreeParams) GetRtreeNamespace() []byte {
	if m != nil {
		return m.RtreeNamespace
	}
	return nil
}

func (m *BuildRTreeParams) GetStatements() []*RTreePolicyStatement {
	if m != nil {
		return m.Statements
	}
	return nil
}

type BuildRTreeResponse struct {
	Error    *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Result   *Proof `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
	ProofDER []byte `protobuf:"bytes,3,opt,name=proofDER,proto3" json:"proofDER,omitempty"`
}

func (m *BuildRTreeResponse) Reset()                    { *m = BuildRTreeResponse{} }
func (m *BuildRTreeResponse) String() string            { return proto.CompactTextString(m) }
func (*BuildRTreeResponse) ProtoMessage()               {}
func (*BuildRTreeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *BuildRTreeResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *BuildRTreeResponse) GetResult() *Proof {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *BuildRTreeResponse) GetProofDER() []byte {
	if m != nil {
		return m.ProofDER
	}
	return nil
}

type VerifyProofParams struct {
	ProofDER []byte `protobuf:"bytes,1,opt,name=proofDER,proto3" json:"proofDER,omitempty"`
}

func (m *VerifyProofParams) Reset()                    { *m = VerifyProofParams{} }
func (m *VerifyProofParams) String() string            { return proto.CompactTextString(m) }
func (*VerifyProofParams) ProtoMessage()               {}
func (*VerifyProofParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *VerifyProofParams) GetProofDER() []byte {
	if m != nil {
		return m.ProofDER
	}
	return nil
}

type VerifyProofResponse struct {
	Error  *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Result *Proof `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *VerifyProofResponse) Reset()                    { *m = VerifyProofResponse{} }
func (m *VerifyProofResponse) String() string            { return proto.CompactTextString(m) }
func (*VerifyProofResponse) ProtoMessage()               {}
func (*VerifyProofResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *VerifyProofResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *VerifyProofResponse) GetResult() *Proof {
	if m != nil {
		return m.Result
	}
	return nil
}

type Proof struct {
	Elements        []*Attestation `protobuf:"bytes,1,rep,name=elements" json:"elements,omitempty"`
	Paths           []*ProofPath   `protobuf:"bytes,2,rep,name=paths" json:"paths,omitempty"`
	Policy          *Policy        `protobuf:"bytes,3,opt,name=policy" json:"policy,omitempty"`
	Expiry          int64          `protobuf:"varint,4,opt,name=expiry" json:"expiry,omitempty"`
	Subject         []byte         `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	SubjectLocation *Location      `protobuf:"bytes,6,opt,name=subjectLocation" json:"subjectLocation,omitempty"`
}

func (m *Proof) Reset()                    { *m = Proof{} }
func (m *Proof) String() string            { return proto.CompactTextString(m) }
func (*Proof) ProtoMessage()               {}
func (*Proof) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *Proof) GetElements() []*Attestation {
	if m != nil {
		return m.Elements
	}
	return nil
}

func (m *Proof) GetPaths() []*ProofPath {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *Proof) GetPolicy() *Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *Proof) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *Proof) GetSubject() []byte {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *Proof) GetSubjectLocation() *Location {
	if m != nil {
		return m.SubjectLocation
	}
	return nil
}

type ProofPath struct {
	Elements []int32 `protobuf:"varint,1,rep,packed,name=elements" json:"elements,omitempty"`
}

func (m *ProofPath) Reset()                    { *m = ProofPath{} }
func (m *ProofPath) String() string            { return proto.CompactTextString(m) }
func (*ProofPath) ProtoMessage()               {}
func (*ProofPath) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *ProofPath) GetElements() []int32 {
	if m != nil {
		return m.Elements
	}
	return nil
}

func init() {
	proto.RegisterType((*ResolveHashParams)(nil), "pb.ResolveHashParams")
	proto.RegisterType((*ResolveHashResponse)(nil), "pb.ResolveHashResponse")
	proto.RegisterType((*InspectParams)(nil), "pb.InspectParams")
	proto.RegisterType((*InspectResponse)(nil), "pb.InspectResponse")
	proto.RegisterType((*ListLocationsParams)(nil), "pb.ListLocationsParams")
	proto.RegisterType((*ListLocationsResponse)(nil), "pb.ListLocationsResponse")
	proto.RegisterType((*CreateEntityParams)(nil), "pb.CreateEntityParams")
	proto.RegisterType((*CreateEntityResponse)(nil), "pb.CreateEntityResponse")
	proto.RegisterType((*Entity)(nil), "pb.Entity")
	proto.RegisterType((*CreateAttestationParams)(nil), "pb.CreateAttestationParams")
	proto.RegisterType((*ResyncPerspectiveGraphParams)(nil), "pb.ResyncPerspectiveGraphParams")
	proto.RegisterType((*ResyncPerspectiveGraphResponse)(nil), "pb.ResyncPerspectiveGraphResponse")
	proto.RegisterType((*SyncParams)(nil), "pb.SyncParams")
	proto.RegisterType((*SyncResponse)(nil), "pb.SyncResponse")
	proto.RegisterType((*StorageDriverStatus)(nil), "pb.StorageDriverStatus")
	proto.RegisterType((*CreateAttestationResponse)(nil), "pb.CreateAttestationResponse")
	proto.RegisterType((*PublishEntityParams)(nil), "pb.PublishEntityParams")
	proto.RegisterType((*PublishEntityResponse)(nil), "pb.PublishEntityResponse")
	proto.RegisterType((*PublishAttestationParams)(nil), "pb.PublishAttestationParams")
	proto.RegisterType((*PublishAttestationResponse)(nil), "pb.PublishAttestationResponse")
	proto.RegisterType((*AddAttestationParams)(nil), "pb.AddAttestationParams")
	proto.RegisterType((*AddAttestationResponse)(nil), "pb.AddAttestationResponse")
	proto.RegisterType((*LookupAttestationsParams)(nil), "pb.LookupAttestationsParams")
	proto.RegisterType((*LookupAttestationsResponse)(nil), "pb.LookupAttestationsResponse")
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*Perspective)(nil), "pb.Perspective")
	proto.RegisterType((*Location)(nil), "pb.Location")
	proto.RegisterType((*LocationURI)(nil), "pb.LocationURI")
	proto.RegisterType((*EntitySecret)(nil), "pb.EntitySecret")
	proto.RegisterType((*Attestation)(nil), "pb.Attestation")
	proto.RegisterType((*AttestationBody)(nil), "pb.AttestationBody")
	proto.RegisterType((*AttestationValidity)(nil), "pb.AttestationValidity")
	proto.RegisterType((*EntityValidity)(nil), "pb.EntityValidity")
	proto.RegisterType((*Policy)(nil), "pb.Policy")
	proto.RegisterType((*TrustLevelPolicy)(nil), "pb.TrustLevelPolicy")
	proto.RegisterType((*RTreePolicy)(nil), "pb.RTreePolicy")
	proto.RegisterType((*RTreePolicyStatement)(nil), "pb.RTreePolicyStatement")
	proto.RegisterType((*BuildRTreeParams)(nil), "pb.BuildRTreeParams")
	proto.RegisterType((*BuildRTreeResponse)(nil), "pb.BuildRTreeResponse")
	proto.RegisterType((*VerifyProofParams)(nil), "pb.VerifyProofParams")
	proto.RegisterType((*VerifyProofResponse)(nil), "pb.VerifyProofResponse")
	proto.RegisterType((*Proof)(nil), "pb.Proof")
	proto.RegisterType((*ProofPath)(nil), "pb.ProofPath")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WAVE service

type WAVEClient interface {
	// Create a new WAVE entity, but do not publish it
	CreateEntity(ctx context.Context, in *CreateEntityParams, opts ...grpc.CallOption) (*CreateEntityResponse, error)
	// Create a WAVE attestation, both the source and destination entities must
	// be published
	CreateAttestation(ctx context.Context, in *CreateAttestationParams, opts ...grpc.CallOption) (*CreateAttestationResponse, error)
	// Publish the given entity
	PublishEntity(ctx context.Context, in *PublishEntityParams, opts ...grpc.CallOption) (*PublishEntityResponse, error)
	// Publish an attestation
	PublishAttestation(ctx context.Context, in *PublishAttestationParams, opts ...grpc.CallOption) (*PublishAttestationResponse, error)
	// Add an attestation to the given perspective graph
	AddAttestation(ctx context.Context, in *AddAttestationParams, opts ...grpc.CallOption) (*AddAttestationResponse, error)
	LookupAttestations(ctx context.Context, in *LookupAttestationsParams, opts ...grpc.CallOption) (*LookupAttestationsResponse, error)
	ResyncPerspectiveGraph(ctx context.Context, in *ResyncPerspectiveGraphParams, opts ...grpc.CallOption) (*ResyncPerspectiveGraphResponse, error)
	SyncStatus(ctx context.Context, in *SyncParams, opts ...grpc.CallOption) (*SyncResponse, error)
	WaitForSyncComplete(ctx context.Context, in *SyncParams, opts ...grpc.CallOption) (WAVE_WaitForSyncCompleteClient, error)
	BuildRTreeProof(ctx context.Context, in *BuildRTreeParams, opts ...grpc.CallOption) (*BuildRTreeResponse, error)
	VerifyProof(ctx context.Context, in *VerifyProofParams, opts ...grpc.CallOption) (*VerifyProofResponse, error)
	ListLocations(ctx context.Context, in *ListLocationsParams, opts ...grpc.CallOption) (*ListLocationsResponse, error)
	Inspect(ctx context.Context, in *InspectParams, opts ...grpc.CallOption) (*InspectResponse, error)
	ResolveHash(ctx context.Context, in *ResolveHashParams, opts ...grpc.CallOption) (*ResolveHashResponse, error)
}

type wAVEClient struct {
	cc *grpc.ClientConn
}

func NewWAVEClient(cc *grpc.ClientConn) WAVEClient {
	return &wAVEClient{cc}
}

func (c *wAVEClient) CreateEntity(ctx context.Context, in *CreateEntityParams, opts ...grpc.CallOption) (*CreateEntityResponse, error) {
	out := new(CreateEntityResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/CreateEntity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEClient) CreateAttestation(ctx context.Context, in *CreateAttestationParams, opts ...grpc.CallOption) (*CreateAttestationResponse, error) {
	out := new(CreateAttestationResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/CreateAttestation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEClient) PublishEntity(ctx context.Context, in *PublishEntityParams, opts ...grpc.CallOption) (*PublishEntityResponse, error) {
	out := new(PublishEntityResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/PublishEntity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEClient) PublishAttestation(ctx context.Context, in *PublishAttestationParams, opts ...grpc.CallOption) (*PublishAttestationResponse, error) {
	out := new(PublishAttestationResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/PublishAttestation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEClient) AddAttestation(ctx context.Context, in *AddAttestationParams, opts ...grpc.CallOption) (*AddAttestationResponse, error) {
	out := new(AddAttestationResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/AddAttestation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEClient) LookupAttestations(ctx context.Context, in *LookupAttestationsParams, opts ...grpc.CallOption) (*LookupAttestationsResponse, error) {
	out := new(LookupAttestationsResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/LookupAttestations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEClient) ResyncPerspectiveGraph(ctx context.Context, in *ResyncPerspectiveGraphParams, opts ...grpc.CallOption) (*ResyncPerspectiveGraphResponse, error) {
	out := new(ResyncPerspectiveGraphResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/ResyncPerspectiveGraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEClient) SyncStatus(ctx context.Context, in *SyncParams, opts ...grpc.CallOption) (*SyncResponse, error) {
	out := new(SyncResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/SyncStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEClient) WaitForSyncComplete(ctx context.Context, in *SyncParams, opts ...grpc.CallOption) (WAVE_WaitForSyncCompleteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_WAVE_serviceDesc.Streams[0], c.cc, "/pb.WAVE/WaitForSyncComplete", opts...)
	if err != nil {
		return nil, err
	}
	x := &wAVEWaitForSyncCompleteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WAVE_WaitForSyncCompleteClient interface {
	Recv() (*SyncResponse, error)
	grpc.ClientStream
}

type wAVEWaitForSyncCompleteClient struct {
	grpc.ClientStream
}

func (x *wAVEWaitForSyncCompleteClient) Recv() (*SyncResponse, error) {
	m := new(SyncResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wAVEClient) BuildRTreeProof(ctx context.Context, in *BuildRTreeParams, opts ...grpc.CallOption) (*BuildRTreeResponse, error) {
	out := new(BuildRTreeResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/BuildRTreeProof", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEClient) VerifyProof(ctx context.Context, in *VerifyProofParams, opts ...grpc.CallOption) (*VerifyProofResponse, error) {
	out := new(VerifyProofResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/VerifyProof", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEClient) ListLocations(ctx context.Context, in *ListLocationsParams, opts ...grpc.CallOption) (*ListLocationsResponse, error) {
	out := new(ListLocationsResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/ListLocations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEClient) Inspect(ctx context.Context, in *InspectParams, opts ...grpc.CallOption) (*InspectResponse, error) {
	out := new(InspectResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/Inspect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wAVEClient) ResolveHash(ctx context.Context, in *ResolveHashParams, opts ...grpc.CallOption) (*ResolveHashResponse, error) {
	out := new(ResolveHashResponse)
	err := grpc.Invoke(ctx, "/pb.WAVE/ResolveHash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WAVE service

type WAVEServer interface {
	// Create a new WAVE entity, but do not publish it
	CreateEntity(context.Context, *CreateEntityParams) (*CreateEntityResponse, error)
	// Create a WAVE attestation, both the source and destination entities must
	// be published
	CreateAttestation(context.Context, *CreateAttestationParams) (*CreateAttestationResponse, error)
	// Publish the given entity
	PublishEntity(context.Context, *PublishEntityParams) (*PublishEntityResponse, error)
	// Publish an attestation
	PublishAttestation(context.Context, *PublishAttestationParams) (*PublishAttestationResponse, error)
	// Add an attestation to the given perspective graph
	AddAttestation(context.Context, *AddAttestationParams) (*AddAttestationResponse, error)
	LookupAttestations(context.Context, *LookupAttestationsParams) (*LookupAttestationsResponse, error)
	ResyncPerspectiveGraph(context.Context, *ResyncPerspectiveGraphParams) (*ResyncPerspectiveGraphResponse, error)
	SyncStatus(context.Context, *SyncParams) (*SyncResponse, error)
	WaitForSyncComplete(*SyncParams, WAVE_WaitForSyncCompleteServer) error
	BuildRTreeProof(context.Context, *BuildRTreeParams) (*BuildRTreeResponse, error)
	VerifyProof(context.Context, *VerifyProofParams) (*VerifyProofResponse, error)
	ListLocations(context.Context, *ListLocationsParams) (*ListLocationsResponse, error)
	Inspect(context.Context, *InspectParams) (*InspectResponse, error)
	ResolveHash(context.Context, *ResolveHashParams) (*ResolveHashResponse, error)
}

func RegisterWAVEServer(s *grpc.Server, srv WAVEServer) {
	s.RegisterService(&_WAVE_serviceDesc, srv)
}

func _WAVE_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntityParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/CreateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).CreateEntity(ctx, req.(*CreateEntityParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVE_CreateAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttestationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).CreateAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/CreateAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).CreateAttestation(ctx, req.(*CreateAttestationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVE_PublishEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEntityParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).PublishEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/PublishEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).PublishEntity(ctx, req.(*PublishEntityParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVE_PublishAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishAttestationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).PublishAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/PublishAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).PublishAttestation(ctx, req.(*PublishAttestationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVE_AddAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAttestationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).AddAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/AddAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).AddAttestation(ctx, req.(*AddAttestationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVE_LookupAttestations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupAttestationsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).LookupAttestations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/LookupAttestations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).LookupAttestations(ctx, req.(*LookupAttestationsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVE_ResyncPerspectiveGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResyncPerspectiveGraphParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).ResyncPerspectiveGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/ResyncPerspectiveGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).ResyncPerspectiveGraph(ctx, req.(*ResyncPerspectiveGraphParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVE_SyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).SyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/SyncStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).SyncStatus(ctx, req.(*SyncParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVE_WaitForSyncComplete_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WAVEServer).WaitForSyncComplete(m, &wAVEWaitForSyncCompleteServer{stream})
}

type WAVE_WaitForSyncCompleteServer interface {
	Send(*SyncResponse) error
	grpc.ServerStream
}

type wAVEWaitForSyncCompleteServer struct {
	grpc.ServerStream
}

func (x *wAVEWaitForSyncCompleteServer) Send(m *SyncResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _WAVE_BuildRTreeProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRTreeParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).BuildRTreeProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/BuildRTreeProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).BuildRTreeProof(ctx, req.(*BuildRTreeParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVE_VerifyProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyProofParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).VerifyProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/VerifyProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).VerifyProof(ctx, req.(*VerifyProofParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVE_ListLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLocationsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).ListLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/ListLocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).ListLocations(ctx, req.(*ListLocationsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVE_Inspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).Inspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/Inspect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).Inspect(ctx, req.(*InspectParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAVE_ResolveHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveHashParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAVEServer).ResolveHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WAVE/ResolveHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAVEServer).ResolveHash(ctx, req.(*ResolveHashParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _WAVE_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.WAVE",
	HandlerType: (*WAVEServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntity",
			Handler:    _WAVE_CreateEntity_Handler,
		},
		{
			MethodName: "CreateAttestation",
			Handler:    _WAVE_CreateAttestation_Handler,
		},
		{
			MethodName: "PublishEntity",
			Handler:    _WAVE_PublishEntity_Handler,
		},
		{
			MethodName: "PublishAttestation",
			Handler:    _WAVE_PublishAttestation_Handler,
		},
		{
			MethodName: "AddAttestation",
			Handler:    _WAVE_AddAttestation_Handler,
		},
		{
			MethodName: "LookupAttestations",
			Handler:    _WAVE_LookupAttestations_Handler,
		},
		{
			MethodName: "ResyncPerspectiveGraph",
			Handler:    _WAVE_ResyncPerspectiveGraph_Handler,
		},
		{
			MethodName: "SyncStatus",
			Handler:    _WAVE_SyncStatus_Handler,
		},
		{
			MethodName: "BuildRTreeProof",
			Handler:    _WAVE_BuildRTreeProof_Handler,
		},
		{
			MethodName: "VerifyProof",
			Handler:    _WAVE_VerifyProof_Handler,
		},
		{
			MethodName: "ListLocations",
			Handler:    _WAVE_ListLocations_Handler,
		},
		{
			MethodName: "Inspect",
			Handler:    _WAVE_Inspect_Handler,
		},
		{
			MethodName: "ResolveHash",
			Handler:    _WAVE_ResolveHash_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WaitForSyncComplete",
			Handler:       _WAVE_WaitForSyncComplete_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "eapi.proto",
}

func init() { proto.RegisterFile("eapi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2077 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x59, 0x4f, 0x6f, 0x1c, 0x49,
	0x15, 0x57, 0xcf, 0x3f, 0xcf, 0xbc, 0x19, 0xdb, 0xe3, 0x1a, 0xdb, 0x99, 0x74, 0xbc, 0x59, 0xa7,
	0x16, 0x76, 0x4d, 0x60, 0x6d, 0x92, 0x65, 0x21, 0x89, 0x90, 0x58, 0xef, 0xc6, 0xcb, 0x5a, 0x58,
	0xe0, 0x94, 0x37, 0x59, 0x05, 0x09, 0xa1, 0xf6, 0x74, 0xd9, 0xd3, 0x64, 0xa6, 0xbb, 0xb7, 0xba,
	0x66, 0xc4, 0x20, 0x71, 0x41, 0x42, 0x68, 0x39, 0xc2, 0x37, 0xe0, 0x02, 0x12, 0x07, 0x8e, 0x5c,
	0xf8, 0x02, 0x7b, 0xe6, 0x0b, 0x20, 0x84, 0xc4, 0x67, 0x40, 0x5c, 0x50, 0xfd, 0xe9, 0xee, 0xaa,
	0xee, 0x76, 0x32, 0x24, 0xab, 0xbd, 0x75, 0xfd, 0xde, 0xab, 0xf7, 0xaf, 0x5e, 0xbd, 0x7a, 0x55,
	0x0d, 0x40, 0xbd, 0x38, 0xd8, 0x8f, 0x59, 0xc4, 0x23, 0x54, 0x8b, 0xcf, 0xdd, 0x9d, 0xcb, 0x28,
	0xba, 0x9c, 0xd0, 0x03, 0x2f, 0x0e, 0x0e, 0xbc, 0x30, 0x8c, 0xb8, 0xc7, 0x83, 0x28, 0x4c, 0x14,
	0x07, 0xfe, 0x31, 0x6c, 0x10, 0x9a, 0x44, 0x93, 0x39, 0xfd, 0xc8, 0x4b, 0xc6, 0xa7, 0x1e, 0xf3,
	0xa6, 0x09, 0x42, 0xd0, 0x18, 0x7b, 0xc9, 0x78, 0xe8, 0xec, 0x3a, 0x7b, 0x3d, 0x22, 0xbf, 0xd1,
	0x1d, 0xe8, 0xc6, 0x94, 0x25, 0x31, 0x1d, 0xf1, 0x60, 0x4e, 0x87, 0xb5, 0x5d, 0x67, 0xaf, 0x7b,
	0x77, 0x7d, 0x3f, 0x3e, 0xdf, 0x3f, 0xcd, 0x61, 0x62, 0xf2, 0xe0, 0xbf, 0x3a, 0x30, 0x30, 0x84,
	0x13, 0x9a, 0xc4, 0x51, 0x98, 0x50, 0xf4, 0x3a, 0x34, 0x29, 0x63, 0x11, 0x93, 0xf2, 0xbb, 0x77,
	0x3b, 0x42, 0xc8, 0x91, 0x00, 0x88, 0xc2, 0xd1, 0x1e, 0xb4, 0x27, 0xd1, 0x48, 0xda, 0xa9, 0x15,
	0xf5, 0x04, 0xcf, 0x89, 0xc6, 0x48, 0x46, 0x45, 0x18, 0x5a, 0x34, 0xe4, 0x01, 0x5f, 0x0c, 0xeb,
	0x92, 0x0f, 0xa4, 0x2c, 0x89, 0x10, 0x4d, 0x11, 0x96, 0x7b, 0x9c, 0xd3, 0x44, 0x39, 0x3e, 0x6c,
	0xe4, 0x96, 0x1f, 0xe6, 0x30, 0x31, 0x79, 0x70, 0x00, 0xab, 0xc7, 0xa1, 0xf4, 0x43, 0x47, 0x64,
	0x08, 0x2b, 0xa3, 0x28, 0xe4, 0x34, 0xe4, 0x3a, 0x28, 0xe9, 0x10, 0xed, 0x40, 0x27, 0x66, 0xd1,
	0x9c, 0xb2, 0x1f, 0xd0, 0x85, 0x34, 0xb6, 0x47, 0x72, 0x00, 0xed, 0x42, 0x77, 0x4e, 0x59, 0x70,
	0x11, 0x28, 0x7a, 0x5d, 0xd2, 0x4d, 0x08, 0x7f, 0xe6, 0xc0, 0xba, 0xd6, 0xb5, 0x7c, 0x80, 0x72,
	0xb7, 0x6b, 0xcb, 0xba, 0x5d, 0x5f, 0xc2, 0xed, 0x2d, 0x18, 0x9c, 0x04, 0x09, 0x4f, 0xe3, 0x9c,
	0x28, 0xe7, 0xf1, 0x3f, 0x1c, 0xd8, 0xb2, 0xf0, 0xe5, 0x0d, 0x7d, 0x0c, 0x6b, 0xde, 0x25, 0x0d,
	0xf3, 0xa9, 0xc3, 0xda, 0x6e, 0x7d, 0xaf, 0x7b, 0xf7, 0x6d, 0xb9, 0x9e, 0x55, 0x32, 0xf7, 0x0f,
	0x2d, 0xfe, 0xa3, 0x90, 0xb3, 0x05, 0x29, 0x08, 0x71, 0x7f, 0x04, 0x83, 0x0a, 0x36, 0xd4, 0x87,
	0xfa, 0x33, 0xba, 0x90, 0xc6, 0x74, 0x88, 0xf8, 0x44, 0x18, 0x9a, 0x73, 0x6f, 0x32, 0xa3, 0x95,
	0x69, 0xa4, 0x48, 0x0f, 0x6a, 0xf7, 0x1c, 0xfc, 0x37, 0x07, 0xd0, 0x07, 0x8c, 0x7a, 0x9c, 0xaa,
	0x28, 0xea, 0x65, 0xdf, 0x81, 0xce, 0xdc, 0x9b, 0x04, 0xfe, 0x87, 0x2c, 0x9a, 0x4a, 0xb1, 0x75,
	0x92, 0x03, 0xe8, 0x26, 0x80, 0x1c, 0x3c, 0x0e, 0x79, 0x30, 0x91, 0x1a, 0xea, 0xc4, 0x40, 0xd0,
	0x77, 0x01, 0x31, 0x3a, 0xd7, 0xda, 0x52, 0xad, 0x7a, 0x21, 0x6c, 0x4b, 0x2a, 0xf8, 0xd0, 0x6d,
	0xe8, 0x9f, 0xd1, 0x11, 0xa3, 0xfc, 0xd4, 0x4b, 0x92, 0x78, 0xcc, 0xbc, 0x84, 0xca, 0xdc, 0xed,
	0x90, 0x7e, 0x52, 0xc0, 0xf1, 0x6f, 0x1c, 0xd8, 0x34, 0xcd, 0x5f, 0x7e, 0x81, 0x76, 0xa0, 0x73,
	0x3a, 0x3b, 0x9f, 0x04, 0xa3, 0x87, 0x47, 0x24, 0x4b, 0xdf, 0x14, 0x10, 0x54, 0x65, 0x83, 0xa0,
	0xaa, 0xe4, 0xed, 0x24, 0x29, 0x90, 0x95, 0x89, 0x46, 0x5e, 0x26, 0xf0, 0x6f, 0x1d, 0x68, 0x29,
	0x1b, 0x2a, 0xab, 0x88, 0x15, 0xd0, 0xda, 0xf3, 0x03, 0x5a, 0x2f, 0x05, 0x74, 0x1f, 0xda, 0x72,
	0x24, 0x12, 0x5f, 0x6d, 0x63, 0x94, 0x27, 0xfe, 0x13, 0x4d, 0x21, 0x19, 0x0f, 0xfe, 0x53, 0x0d,
	0xae, 0xa9, 0xb0, 0x18, 0x29, 0xaf, 0x97, 0xb6, 0x50, 0xcf, 0x9c, 0x17, 0xd7, 0x33, 0x61, 0xde,
	0x79, 0xe4, 0x2f, 0xce, 0x46, 0x63, 0x3a, 0x55, 0x19, 0xd5, 0x21, 0x06, 0x22, 0x36, 0x7b, 0x32,
	0x3b, 0xff, 0x19, 0x1d, 0x71, 0x51, 0xee, 0xd2, 0xcd, 0x6e, 0x40, 0xe8, 0xdb, 0xb0, 0xae, 0x87,
	0x59, 0x3a, 0x34, 0x2a, 0xd2, 0xa1, 0xc8, 0x64, 0x87, 0xad, 0xf9, 0xfc, 0xb0, 0xb5, 0x4a, 0x61,
	0xc3, 0xd0, 0x8a, 0xa3, 0x49, 0x30, 0x5a, 0x0c, 0x57, 0xf2, 0x6a, 0x71, 0x2a, 0x11, 0xa2, 0x29,
	0xf8, 0x11, 0xec, 0x10, 0x9a, 0x2c, 0xc2, 0x91, 0xe1, 0xfd, 0xf7, 0x99, 0x17, 0x8f, 0x5f, 0x3a,
	0x5c, 0xf8, 0x10, 0x6e, 0x56, 0x8b, 0x5c, 0x3a, 0x3b, 0xf1, 0xf7, 0x00, 0xce, 0x84, 0x80, 0x97,
	0xb6, 0xe1, 0xcf, 0x35, 0xe8, 0x09, 0x09, 0xcb, 0x6f, 0x88, 0x63, 0x58, 0x4d, 0x78, 0xc4, 0xbc,
	0x4b, 0x7a, 0xc6, 0x3d, 0x3e, 0x4b, 0x0b, 0xd6, 0x1b, 0x82, 0xd1, 0x94, 0xb4, 0x7f, 0x66, 0x72,
	0xa9, 0x32, 0x65, 0xcf, 0x44, 0xdf, 0x80, 0x0d, 0x1e, 0x71, 0x6f, 0xa2, 0xa6, 0x7d, 0x3a, 0xa3,
	0x09, 0x4f, 0x74, 0x56, 0x97, 0x09, 0xe8, 0x4d, 0x58, 0x1b, 0x45, 0xd3, 0x78, 0x42, 0x39, 0xf5,
	0x05, 0x21, 0x91, 0xa9, 0x51, 0x27, 0x05, 0xd4, 0x7d, 0x0a, 0xa8, 0xac, 0xba, 0xa2, 0xf4, 0xbd,
	0x6d, 0x97, 0xbe, 0x6b, 0xd2, 0x01, 0x35, 0xf1, 0x21, 0x0b, 0xe6, 0x94, 0xa9, 0xe9, 0x66, 0x15,
	0xfc, 0xa3, 0x03, 0x83, 0x0a, 0x16, 0x91, 0xd8, 0x51, 0x4c, 0x99, 0xcc, 0x45, 0x6f, 0x22, 0x95,
	0xb4, 0x89, 0x09, 0xa1, 0x77, 0xa1, 0x11, 0x84, 0x17, 0x91, 0x0e, 0xd6, 0xad, 0x2b, 0x74, 0xed,
	0x1f, 0x87, 0x17, 0x91, 0x0a, 0x95, 0x64, 0x77, 0xbf, 0x03, 0x9d, 0x0c, 0xaa, 0x70, 0x61, 0xd3,
	0x74, 0xa1, 0x63, 0x5a, 0xfa, 0x07, 0x07, 0xae, 0x97, 0x76, 0xf6, 0xf2, 0x8b, 0xdc, 0x87, 0x7a,
	0x5e, 0xef, 0xea, 0xfe, 0x11, 0x79, 0xf1, 0x41, 0x6d, 0x1f, 0xf4, 0x8d, 0xe2, 0x41, 0x9f, 0x16,
	0xbb, 0xa6, 0x51, 0x0b, 0x1f, 0xc1, 0x40, 0xd6, 0xd6, 0x64, 0x6c, 0x1d, 0x2a, 0x5a, 0xb9, 0x93,
	0x2b, 0x5f, 0xba, 0xdf, 0xc1, 0x27, 0xb0, 0x65, 0x89, 0x5c, 0xde, 0xe5, 0xd4, 0xc0, 0x9a, 0x61,
	0xe0, 0x13, 0x18, 0x6a, 0x69, 0xe5, 0xfa, 0xf8, 0x2a, 0x56, 0x3e, 0x02, 0xb7, 0x2c, 0xf7, 0xd5,
	0x4c, 0x5d, 0xc0, 0xe6, 0xa1, 0xef, 0x7f, 0x21, 0x65, 0xbc, 0xbc, 0xf8, 0xd6, 0xd2, 0xd6, 0x0b,
	0x4b, 0x8b, 0xef, 0xc3, 0xb6, 0xad, 0x7a, 0xf9, 0xfa, 0xf5, 0x99, 0x03, 0xc3, 0x93, 0x28, 0x7a,
	0x36, 0x8b, 0x8d, 0xe9, 0xc9, 0x2b, 0x9d, 0x40, 0x17, 0x2c, 0x9a, 0x1e, 0xe5, 0xbd, 0x5f, 0x8f,
	0x18, 0x08, 0x72, 0xa1, 0xcd, 0xa3, 0xa3, 0xbc, 0x21, 0xee, 0x91, 0x6c, 0x8c, 0xc7, 0xe0, 0x96,
	0x4d, 0x59, 0x7e, 0x51, 0xbe, 0x06, 0x2b, 0x8c, 0x26, 0xb3, 0x09, 0x4f, 0x2b, 0x62, 0xa9, 0x95,
	0x4c, 0xe9, 0xf8, 0x5d, 0x68, 0x1e, 0xa5, 0x0b, 0x39, 0x8a, 0x7c, 0xe5, 0x5a, 0x93, 0xc8, 0x6f,
	0xd1, 0x49, 0x4f, 0x69, 0x92, 0x78, 0x97, 0xe9, 0xae, 0x4e, 0x87, 0x78, 0x0a, 0x5d, 0xc3, 0x71,
	0xf4, 0x2d, 0xe8, 0xa9, 0x4e, 0x56, 0x75, 0x20, 0xda, 0xb0, 0x7e, 0x7e, 0xe0, 0x2b, 0x9c, 0x58,
	0x5c, 0xff, 0x47, 0x92, 0x8e, 0xa0, 0x9d, 0x9d, 0xaf, 0x77, 0xa0, 0x9b, 0xe2, 0x8f, 0xc9, 0xb1,
	0xb9, 0x14, 0x27, 0x39, 0x4c, 0x4c, 0x1e, 0xf4, 0x15, 0x58, 0xb5, 0x9a, 0x52, 0xed, 0x8d, 0x0d,
	0xe2, 0xfb, 0xd0, 0x35, 0x24, 0x88, 0xd4, 0x4b, 0xe5, 0x77, 0x48, 0x7d, 0x46, 0x8e, 0x45, 0x38,
	0xe6, 0x94, 0x25, 0xa9, 0x80, 0x26, 0x49, 0x87, 0xf8, 0x3d, 0xe8, 0x99, 0x7e, 0x56, 0x6c, 0xc8,
	0x9b, 0x00, 0x71, 0xde, 0x1b, 0xea, 0x6c, 0xc8, 0x11, 0xfc, 0x79, 0x0d, 0xba, 0xc6, 0x02, 0x55,
	0x48, 0xa8, 0xd8, 0x69, 0xe8, 0x2d, 0x68, 0x88, 0x9e, 0x46, 0xf7, 0xa9, 0x83, 0xc2, 0x2a, 0xbf,
	0x1f, 0xf9, 0x0b, 0x22, 0x19, 0x8a, 0x25, 0xb3, 0xf1, 0x82, 0x92, 0xd9, 0xac, 0xb8, 0x1b, 0x99,
	0xed, 0x52, 0x6b, 0xa9, 0x76, 0x69, 0x65, 0x99, 0x76, 0xe9, 0x1d, 0xa3, 0x4f, 0x6c, 0xe7, 0xa7,
	0x9f, 0xe1, 0x46, 0xb9, 0x59, 0x94, 0xc6, 0x7a, 0x8c, 0x07, 0x52, 0x4d, 0x67, 0xb7, 0x2e, 0x8d,
	0x4d, 0x01, 0xfc, 0x1f, 0x07, 0xd6, 0x0b, 0x61, 0x10, 0x27, 0xf6, 0x43, 0x2a, 0x92, 0xda, 0x17,
	0xc3, 0x3c, 0xb4, 0x6b, 0xbe, 0x85, 0x22, 0x0c, 0x3d, 0x75, 0xcb, 0xa2, 0xec, 0xa3, 0x3c, 0xda,
	0x16, 0x86, 0xee, 0x41, 0x3f, 0x1d, 0x3f, 0xf7, 0xa6, 0x50, 0xe2, 0x32, 0xba, 0xbb, 0xc6, 0x55,
	0xdd, 0xdd, 0xab, 0xf5, 0x8f, 0xf8, 0xbf, 0x0e, 0x0c, 0x2a, 0x62, 0xa7, 0x8f, 0xe7, 0xc0, 0xd7,
	0x0d, 0x81, 0x1a, 0x88, 0x8c, 0x16, 0xb7, 0x99, 0x67, 0xd4, 0x97, 0x8e, 0xb6, 0x49, 0x3a, 0x14,
	0x14, 0xfa, 0xf3, 0x38, 0x60, 0xd4, 0x97, 0xae, 0xb5, 0x49, 0x3a, 0x14, 0xf6, 0x4d, 0xbd, 0xc9,
	0x45, 0xc4, 0xa6, 0xd4, 0x97, 0x6e, 0xb4, 0x49, 0x0e, 0x88, 0xf8, 0x85, 0x11, 0x7f, 0x48, 0x47,
	0x6c, 0x11, 0x73, 0xea, 0x4b, 0x07, 0xda, 0xc4, 0xc2, 0x84, 0x0f, 0x09, 0x1b, 0x1d, 0x87, 0xca,
	0xa0, 0x96, 0xe4, 0x30, 0x10, 0x41, 0xf7, 0x13, 0x9e, 0xd2, 0x57, 0x14, 0x3d, 0x47, 0xcc, 0xb2,
	0xd4, 0xb6, 0xcb, 0xd2, 0xef, 0x1c, 0x58, 0xb3, 0x6f, 0x18, 0x5f, 0x9a, 0xe3, 0x86, 0x51, 0x4d,
	0xdb, 0xa8, 0x5f, 0x42, 0x4b, 0x2d, 0x31, 0x7a, 0x0f, 0xfa, 0x9c, 0xcd, 0x12, 0x7e, 0x42, 0xe7,
	0x74, 0xa2, 0x30, 0x5d, 0xbf, 0x36, 0x45, 0x22, 0x7c, 0x5c, 0xa0, 0x91, 0x12, 0xb7, 0x28, 0x7e,
	0xec, 0x63, 0x46, 0xa9, 0x9e, 0x6c, 0xbc, 0xec, 0x90, 0x1c, 0x26, 0x26, 0x0f, 0xde, 0x83, 0x7e,
	0x51, 0xb0, 0x08, 0x8a, 0x14, 0xad, 0xab, 0xbd, 0x1a, 0xe0, 0xbf, 0x38, 0xd0, 0x35, 0xc4, 0x08,
	0x87, 0x43, 0x6f, 0x4a, 0x93, 0xd8, 0x1b, 0x51, 0xbd, 0x5d, 0x72, 0x40, 0xac, 0x74, 0x10, 0xfa,
	0x01, 0x13, 0x47, 0x80, 0x7a, 0x2c, 0x70, 0xf6, 0x56, 0x89, 0x85, 0xa1, 0x7b, 0x00, 0x22, 0x11,
	0xe9, 0x94, 0x86, 0xb2, 0x9d, 0x16, 0x67, 0xd1, 0xb0, 0x60, 0xed, 0x59, 0xca, 0x40, 0x0c, 0x5e,
	0x51, 0xb2, 0xe7, 0x41, 0x12, 0x9c, 0x07, 0x93, 0x80, 0x2f, 0x44, 0x1d, 0x6e, 0xc8, 0x5d, 0x6e,
	0x83, 0xf8, 0x17, 0xb0, 0x59, 0x25, 0x49, 0xcc, 0x8e, 0x29, 0x9b, 0x06, 0x89, 0xa8, 0xce, 0x67,
	0x34, 0x7d, 0x08, 0xb2, 0x41, 0x51, 0xd4, 0x72, 0x40, 0x1d, 0x95, 0x1d, 0x62, 0x42, 0xe2, 0x8c,
	0x66, 0x34, 0x89, 0x66, 0x6c, 0x44, 0x65, 0x36, 0x74, 0x48, 0x36, 0xc6, 0x9f, 0x3b, 0xd0, 0x7f,
	0x7f, 0x16, 0x4c, 0x7c, 0x65, 0xc1, 0x4b, 0xf7, 0x09, 0x85, 0xd2, 0x5a, 0x2b, 0x97, 0xd6, 0x37,
	0x61, 0x8d, 0x71, 0x46, 0xe9, 0x0f, 0xb3, 0xc5, 0x50, 0xfd, 0x42, 0x01, 0x2d, 0x44, 0xbb, 0xb1,
	0x7c, 0xb4, 0x31, 0x07, 0x94, 0xbb, 0xb2, 0x7c, 0x9f, 0x71, 0x0b, 0x5a, 0xaa, 0x8f, 0xd0, 0x89,
	0x28, 0x39, 0x4e, 0x59, 0x14, 0x5d, 0x10, 0x4d, 0x10, 0x11, 0x8c, 0x05, 0x90, 0x3f, 0x4a, 0x64,
	0x63, 0x7c, 0x00, 0x1b, 0x4f, 0xc4, 0x09, 0xb4, 0x90, 0x53, 0x74, 0x04, 0xcd, 0x09, 0x4e, 0x61,
	0xc2, 0x53, 0x18, 0x18, 0x13, 0xbe, 0x48, 0x3b, 0xf1, 0xbf, 0x1d, 0x68, 0x4a, 0x04, 0x7d, 0x1d,
	0xda, 0x74, 0xa2, 0x63, 0xe8, 0x54, 0x77, 0x4f, 0x19, 0x03, 0x7a, 0x03, 0x9a, 0xb1, 0xc7, 0xc7,
	0x69, 0x9f, 0xb5, 0x9a, 0x09, 0x3e, 0xf5, 0xf8, 0x98, 0x28, 0x9a, 0x51, 0xf5, 0xeb, 0x57, 0x56,
	0xfd, 0x6d, 0x68, 0xc9, 0x3a, 0xb3, 0xd0, 0x37, 0x49, 0x3d, 0x12, 0x65, 0x45, 0xa7, 0x82, 0x3e,
	0x94, 0xd3, 0x61, 0xd5, 0x81, 0xdb, 0x5a, 0xe2, 0xc0, 0xc5, 0x6f, 0x41, 0x27, 0xb3, 0x50, 0x44,
	0xdb, 0x72, 0xb6, 0x99, 0xfb, 0x76, 0xf7, 0x9f, 0x00, 0x8d, 0x4f, 0x0e, 0x9f, 0x1c, 0xa1, 0x9f,
	0x40, 0xcf, 0x7c, 0xb0, 0x42, 0xdb, 0x42, 0x41, 0xf9, 0x05, 0xce, 0x1d, 0x16, 0xf1, 0x74, 0x85,
	0xf0, 0x8d, 0x5f, 0xfd, 0xfd, 0x5f, 0xbf, 0xaf, 0x6d, 0xe1, 0xfe, 0xc1, 0xfc, 0xce, 0x81, 0xc9,
	0xf1, 0xc0, 0xb9, 0x8d, 0x3e, 0x85, 0x8d, 0xd2, 0xf5, 0x10, 0xdd, 0xc8, 0x65, 0x95, 0x2e, 0x12,
	0xee, 0x6b, 0x95, 0xc4, 0x4c, 0xdb, 0xae, 0xd4, 0xe6, 0xe2, 0xad, 0x5c, 0x9b, 0xc1, 0x26, 0x54,
	0x7a, 0xb0, 0x6a, 0x5d, 0xcd, 0x90, 0xec, 0x39, 0x2a, 0x2e, 0x80, 0xee, 0xf5, 0x12, 0x21, 0x53,
	0xb3, 0x23, 0xd5, 0x6c, 0xe3, 0x0d, 0xa1, 0xc6, 0x62, 0x11, 0x2a, 0x66, 0x80, 0xca, 0xf7, 0x2a,
	0xb4, 0x63, 0x88, 0x2b, 0xfb, 0x75, 0xb3, 0x9a, 0x9a, 0x69, 0xbc, 0x25, 0x35, 0xde, 0xc0, 0xdb,
	0x86, 0xc6, 0x82, 0x67, 0x14, 0xd6, 0xec, 0x0b, 0x10, 0x92, 0xab, 0x52, 0x75, 0x1f, 0x73, 0xdd,
	0x32, 0x25, 0x53, 0xf5, 0x9a, 0x54, 0x75, 0x0d, 0x23, 0xa1, 0xca, 0xe6, 0x11, 0x6a, 0x38, 0xa0,
	0xf2, 0x05, 0x45, 0x79, 0x77, 0xd5, 0x1d, 0x4a, 0x79, 0x77, 0xf5, 0xb5, 0xc6, 0x5e, 0xb6, 0x12,
	0x9f, 0xd0, 0xfa, 0x6b, 0x07, 0xb6, 0xab, 0x9f, 0xa9, 0xd0, 0xae, 0xac, 0x73, 0xcf, 0x79, 0x15,
	0x73, 0xf1, 0xd5, 0x1c, 0x99, 0x09, 0x5f, 0x95, 0x26, 0xbc, 0x8e, 0x5d, 0x61, 0x42, 0x35, 0xaf,
	0xb0, 0xe3, 0x58, 0x3d, 0x75, 0xe9, 0x17, 0x97, 0xb5, 0xf4, 0xb9, 0x49, 0x2b, 0xea, 0x17, 0x9f,
	0x9f, 0xf0, 0x75, 0x29, 0x76, 0x80, 0xd7, 0x84, 0xd8, 0x7c, 0xa6, 0x10, 0x75, 0x1f, 0x06, 0x9f,
	0x78, 0x01, 0xff, 0x30, 0x62, 0x02, 0xff, 0x40, 0x3f, 0x1f, 0xbd, 0x58, 0xe6, 0x37, 0x1d, 0xf4,
	0x53, 0x58, 0x37, 0xce, 0x1f, 0x59, 0xbb, 0x64, 0x1b, 0x51, 0x3c, 0x94, 0xdc, 0x6d, 0x1b, 0xcd,
	0xcc, 0xba, 0x29, 0xcd, 0x1a, 0xe2, 0x81, 0x30, 0xab, 0x20, 0x4a, 0xd8, 0xf6, 0x14, 0xba, 0x46,
	0xb9, 0x45, 0x5b, 0x42, 0x4c, 0xa9, 0x60, 0xbb, 0xd7, 0x0a, 0x70, 0x26, 0xde, 0x95, 0xe2, 0x37,
	0xf1, 0xba, 0x10, 0x6f, 0x30, 0xe8, 0x0d, 0x68, 0xfd, 0x51, 0x50, 0x1b, 0xb0, 0xe2, 0x87, 0x86,
	0xda, 0x80, 0x95, 0x7f, 0x1f, 0xec, 0x0d, 0x68, 0xb1, 0xa8, 0x45, 0x5a, 0xd1, 0xff, 0x6a, 0xd0,
	0x86, 0x90, 0x61, 0xfd, 0x24, 0x72, 0x07, 0x06, 0x94, 0x09, 0xdc, 0x96, 0x02, 0xfb, 0xb8, 0x2b,
	0x04, 0x6a, 0xa2, 0x0e, 0x84, 0xf1, 0x6f, 0x4c, 0x05, 0xa2, 0xf4, 0x27, 0x4e, 0x05, 0xa2, 0xe2,
	0x1f, 0x9a, 0x1d, 0x08, 0x83, 0xe1, 0x81, 0x73, 0xfb, 0xbc, 0x25, 0x7f, 0xed, 0xbd, 0xf3, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x4a, 0xf5, 0xd7, 0x0a, 0x1c, 0x00, 0x00,
}
